# Generated by Django 4.2.21 on 2025-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system_dk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source System DK')),
                ('apartment_offer_rk', models.CharField(max_length=255, verbose_name='Apartment Offer RK')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('hashdiff_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='HashDiff Key')),
                ('actual_flg', models.SmallIntegerField(blank=True, null=True, verbose_name='Actual Flag')),
                ('delete_flg', models.SmallIntegerField(blank=True, null=True, verbose_name='Delete Flag')),
                ('id_offer', models.IntegerField(blank=True, null=True, verbose_name='Offer ID')),
                ('amount_rooms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount of Rooms')),
                ('offer_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer Type')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('square', models.CharField(blank=True, max_length=50, null=True, verbose_name='Square')),
                ('house_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='House Address')),
                ('parking_space', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parking Space')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('phones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phones')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('repair', models.CharField(blank=True, max_length=100, null=True, verbose_name='Repair')),
                ('square_rooms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Square Rooms')),
                ('balcony', models.CharField(blank=True, max_length=100, null=True, verbose_name='Balcony')),
                ('windows_oriention', models.CharField(blank=True, max_length=100, null=True, verbose_name='Windows Orientation')),
                ('bathroom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bathroom')),
                ('is_possible_with_kids_animals', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kids & Animals Allowed')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='Additional Description')),
                ('residential_complex_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential Complex Title')),
                ('ceiling_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ceiling Height')),
                ('lift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lift')),
                ('garbage_chute', models.CharField(blank=True, max_length=50, null=True, verbose_name='Garbage Chute')),
                ('link_to_offer', models.CharField(blank=True, max_length=512, null=True, verbose_name='Link to Offer')),
            ],
            options={
                'verbose_name': 'Apartment Offer',
                'verbose_name_plural': 'Apartment Offers',
                'db_table': 'apartment_offer',
            },
        ),
    ]
