# Generated by Django 4.2.21 on 2025-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentoffer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='amount_rooms',
            field=models.TextField(blank=True, null=True, verbose_name='Amount of Rooms'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='apartment_offer_rk',
            field=models.TextField(verbose_name='Apartment Offer RK'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='balcony',
            field=models.TextField(blank=True, null=True, verbose_name='Balcony'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='bathroom',
            field=models.TextField(blank=True, null=True, verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='ceiling_height',
            field=models.TextField(blank=True, null=True, verbose_name='Ceiling Height'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='garbage_chute',
            field=models.TextField(blank=True, null=True, verbose_name='Garbage Chute'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='hashdiff_key',
            field=models.TextField(blank=True, null=True, verbose_name='HashDiff Key'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='house_address',
            field=models.TextField(blank=True, null=True, verbose_name='House Address'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='is_possible_with_kids_animals',
            field=models.TextField(blank=True, null=True, verbose_name='Kids & Animals Allowed'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='lift',
            field=models.TextField(blank=True, null=True, verbose_name='Lift'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='link_to_offer',
            field=models.TextField(blank=True, null=True, verbose_name='Link to Offer'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='offer_type',
            field=models.TextField(blank=True, null=True, verbose_name='Offer Type'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='parking_space',
            field=models.TextField(blank=True, null=True, verbose_name='Parking Space'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='phones',
            field=models.TextField(blank=True, null=True, verbose_name='Phones'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='price',
            field=models.TextField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='repair',
            field=models.TextField(blank=True, null=True, verbose_name='Repair'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='residential_complex_title',
            field=models.TextField(blank=True, null=True, verbose_name='Residential Complex Title'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='source_system_dk',
            field=models.TextField(blank=True, null=True, verbose_name='Source System DK'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='square',
            field=models.TextField(blank=True, null=True, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='square_rooms',
            field=models.TextField(blank=True, null=True, verbose_name='Square Rooms'),
        ),
        migrations.AlterField(
            model_name='apartmentoffer',
            name='windows_oriention',
            field=models.TextField(blank=True, null=True, verbose_name='Windows Orientation'),
        ),
    ]
